server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017

vault:
  uri: http://vault-dev.services.cvc.com.br:8200
  token: 7t7KdYNWjd8bJnlNma3N9BmO
  authentication: TOKEN
  enabled: false
  generic:
    default-context: gtw-credentials
  config:
    order: -10